Models/KonsoModel.cs
using Konso.Clients.ValueTracking.Interfaces;
using Konso.Clients.ValueTracking.Models;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.Net.Http.Headers;

namespace todo.Models
{
    public class KonsoModel : PageModel
    {
        internal readonly IValueTrackingClient _valueTrackingService;

        public KonsoModel(IValueTrackingClient valueTrackingService)
        {
            _valueTrackingService = valueTrackingService;
        }

        internal async Task TrackValue(string user, ValueTrackingTypes type, double? value = null)
        {
            await _valueTrackingService.CreateAsync(new ValueTrackingCreateRequest()
            {
                IP = Request != null ? Request.HttpContext.Connection.RemoteIpAddress.ToString() : string.Empty,
                EventId = (int)type,
                User = user,
                Value = value,
                CorrelationId = Request.HttpContext.Session.Id,
                Browser = Request.Headers[HeaderNames.UserAgent],
                AppName = "todoapp",
                Tags = new List<string>() { Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") }
            });
        }
    }
}

Models/ValueTrackingTypes.cs
namespace todo.Models
{
    public enum ValueTrackingTypes
    {
        CreateTask = 1, UpdateTask = 2, DeleteTask = 3,
    }
}

Pages/Create.cshtml.cs
using Konso.Clients.ValueTracking.Interfaces;
using Microsoft.AspNetCore.Mvc;
using todo.Abstractions;
using todo.Data;
using todo.Models;

namespace todo.Pages
{
    public class CreateModel : KonsoModel
    {
        private readonly ToDoDbContext _context;
        private readonly ILogger _logger;

        public CreateModel(ToDoDbContext context, ILogger<CreateModel> logger, IValueTrackingClient valueTrackingService) : base(valueTrackingService)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ToDoItem ToDo{ get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            _logger.LogInformation("Calling Post method");
            if (!ModelState.IsValid)
            {
                _logger.LogWarning("Model is invalid");
                return Page();
            }
            _logger.LogWarning($"Warning");
            _logger.LogError($"Error");
            _logger.LogDebug($"Debug");
            _logger.LogCritical($"Critical");
            _logger.LogTrace($"Trace");
            //_logger.LogDebug($"Todo object {JsonSerializer.Serialize(ToDo)}");
            _context.ToDos.Add(ToDo);
            _logger.LogInformation("Saving to database");
            await _context.SaveChangesAsync();
            await TrackValue("test@user.com", ValueTrackingTypes.CreateTask);
            _logger.LogInformation("Ending Post method");
            return RedirectToPage("./Index");
        }
    }
}

Pages/Edit.cshtml.cs
using Konso.Clients.ValueTracking.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using todo.Abstractions;
using todo.Data;
using todo.Models;

namespace todo.Pages
{
    public class EditModel : KonsoModel
    {
        private readonly ToDoDbContext _context;

        public EditModel(ToDoDbContext context, IValueTrackingClient valueTrackingService) : base(valueTrackingService)
        {
            _context = context;
        }

        [BindProperty]
        public ToDoItem ToDo { get; set; }

        public async Task<IActionResult> OnGetAsync(int id)
        {
            ToDo = await _context.ToDos.FindAsync(id);

            if (ToDo == null)
            {
                return RedirectToPage("./Index");
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(ToDo).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();

                await TrackValue("test@user.com", ValueTrackingTypes.UpdateTask);
            }
            catch (DbUpdateConcurrencyException)
            {
                throw new Exception($"ToDo item {ToDo.Id} not found!");
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace todo.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Konso.Clients.ValueTracking.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using todo.Abstractions;
using todo.Data;
using todo.Models;

namespace todo.Pages;

public class IndexModel : KonsoModel
{
    private readonly ToDoDbContext _context;
    private readonly ILogger _logger;
    public IndexModel(ToDoDbContext context, ILogger<IndexModel> logger, IValueTrackingClient valueTrackingService) : base(valueTrackingService)
    {
        _context = context;
        _logger = logger;
    }
    public IList<ToDoItem> ToDos { get; set; }
    public async Task OnGetAsync()
    {
        _logger.LogInformation("Getting todo list");
        ToDos = await _context.ToDos.ToListAsync();
        _logger.LogInformation($"Todo list {ToDos.Count} items");
    }

    public async Task<IActionResult> OnPostDeleteAsync(int id)
    {
        var t = await _context.ToDos.FindAsync(id);

        if (t != null)
        {
            _context.ToDos.Remove(t);
            await _context.SaveChangesAsync();

            await TrackValue("test@user.com", ValueTrackingTypes.DeleteTask);
        }

        return RedirectToPage();
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace todo.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Create.cshtml
@page
@model todo.Pages.CreateModel
@{
}

<h3>What need to be done:</h3>

<form method="post">

    <div class="row">
        <div asp-validation-summary="ModelOnly"></div>
        <span asp-validation-for="ToDo.Name"></span>
        <br />
        Name:
        <input asp-for="ToDo.Name" class="form-control" />
    </div>
    <br />
    
    <div class="container">
        <div class="col-md-12 text-center">
            <button type="submit" class="btn btn-success">Save </button>
        </div> 
    </div>
</form>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

Pages/Edit.cshtml
@page "{id:int}"
@model todo.Pages.EditModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<h3>Edit item - @Model.ToDo.Id</h3>
<form method="post">
    <div asp-validation-summary="All"></div>
    <input asp-for="ToDo.Id" type="hidden" />
    <p>
        <div class="row">
            <label asp-for="ToDo.Name"></label>
            <div>
                <input asp-for="ToDo.Name" class="form-control" />
                <span asp-validation-for="ToDo.Name"></span>
            </div>
        </div>
    
    </p>
    
    <p>
        <button type="submit" class="btn btn-success">Save</button>
    </p>
</form>

Pages/Index.cshtml
@page
@model IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "To Do";
}

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var todo in Model.ToDos)
            {
                <tr>
                    <td> @todo.Id  </td>
                    <td>@todo.Name</td>
                    <td>
                        <a asp-page="./Edit" asp-route-id="@todo.Id" class="link-warning">Edit</a> |
                        <button type="submit" asp-page-handler="delete" class="btn btn-primary btn-sm"
                                asp-route-id="@todo.Id">delete
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
   <div>
        <a asp-page="Create" class="btn btn-success btn-sm">Create New</a>
   </div>
    
</form>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - todo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/todo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - todo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>